name: Validate OpenAPI

description: Validates the OpenAPI from the API

runs:
  using: composite

  steps:
    - name: Get OpenAPI YAML as file
      shell: bash
      run: |
        curl -o openapi.yaml http://localhost:1336/openapi.yaml

    # Run Spectral
    - uses: stoplightio/spectral-action@latest
      with:
        file_glob: 'openapi.yaml'

    - name: Kill port for api 1336 for unit tests
      shell: bash
      run: sudo kill -9 $(sudo lsof -t -i:1336)
