# Spectral is a flexible JSON/YAML linter and validator, which can be used for OpenAPI, AsyncAPI, or any other purpose.
# To run Spectral locally:
# > pnpm lint:openapi

# For information on creating custom rulesets, see:
# https://meta.stoplight.io/docs/spectral/01baf06bdd05a-create-a-ruleset

extends: ["spectral:oas"]
